### ISSUE TITLE
Panic in completions

### ISSUE THREAD

**Issue by tiffany352** [murarth/linefeed#3]
I've run into a crash in linefeed that occurs on large completion candidate sets (> 2500). I believe it is due to an edge case in the table formatting code.  I don't know how to reduce the test case further, so it includes a 5000 line long data file.
## Stack trace:

```
thread 'main' panicked at 'attempted to subtract with overflow', /home/tiffany/.cargo/registry/src/github.com-1ecc6299db9ec823/linefeed-0.1.3/src/table.rs:179
stack backtrace:
   1:     0x55588389badf - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x55588389e7fb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x55588389e47f - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x555883893c7e - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x55588389ea41 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x55588389484a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x55588389e9de - rust_begin_unwind
   8:     0x5558838d4b1f - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x5558838d4df8 - core::panicking::panic::heeca72c448510af4
  10:     0x55588384f05c - linefeed::table::format_columns::h1f94a7e8d6bba06c
                        at /home/tiffany/.cargo/registry/src/github.com-1ecc6299db9ec823/linefeed-0.1.3/src/table.rs:179
  11:     0x55588384d235 - _<linefeed..reader..Reader<Term>>::show_completions::hb9daa6a62e6a9f45
                        at /home/tiffany/.cargo/registry/src/github.com-1ecc6299db9ec823/linefeed-0.1.3/src/reader.rs:1238
  12:     0x55588384b487 - _<linefeed..reader..Reader<Term>>::complete_word::h0be37382ffb05573
                        at /home/tiffany/.cargo/registry/src/github.com-1ecc6299db9ec823/linefeed-0.1.3/src/reader.rs:1174
  13:     0x5558838429f5 - _<linefeed..reader..Reader<Term>>::execute_command::h071769149e783f8f
                        at /home/tiffany/.cargo/registry/src/github.com-1ecc6299db9ec823/linefeed-0.1.3/src/reader.rs:741
  14:     0x555883840028 - _<linefeed..reader..Reader<Term>>::execute_sequence::hea2b58e21f9e6827
                        at /home/tiffany/.cargo/registry/src/github.com-1ecc6299db9ec823/linefeed-0.1.3/src/reader.rs:622
  15:     0x555883839677 - _<linefeed..reader..Reader<Term>>::read_line_impl::h68bc3f5dd2d86b57
                        at /home/tiffany/.cargo/registry/src/github.com-1ecc6299db9ec823/linefeed-0.1.3/src/reader.rs:274
  16:     0x555883838ba3 - _<linefeed..reader..Reader<Term>>::read_line::h80dbf3fc505c3d6b
                        at /home/tiffany/.cargo/registry/src/github.com-1ecc6299db9ec823/linefeed-0.1.3/src/reader.rs:247
  17:     0x555883827406 - linefeed_panic::main::hc41c2e9bf0a25304
                        at /mnt/external/tiffany/scripts/linefeed_panic/src/main.rs:32
  18:     0x55588389e0b8 - std::panicking::try::call::hca715a47aa047c49
  19:     0x5558838a605b - __rust_try
  20:     0x5558838a5ffe - __rust_maybe_catch_panic
  21:     0x55588389db5e - std::rt::lang_start::h162055cb2e4b9fe7
  22:     0x55588386a789 - main
  23:     0x7f30a9504730 - __libc_start_main
  24:     0x55588381f2a8 - _start
  25:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/linefeed_panic` (exit code: 101)
```
## Test code:

``` rust
extern crate linefeed;

use linefeed::*;
use std::rc::Rc;

pub struct FooCompleter;

impl Completer<terminal::DefaultTerminal> for FooCompleter {
    fn complete(&self, _word: &str, _reader: &Reader<terminal::DefaultTerminal>,
                _start: usize, _end: usize) -> Option<Vec<Completion>> {
        use std::fs::File;
        use std::io::{BufRead, BufReader};

        let f = BufReader::new(File::open("out.txt").unwrap());
        let lines = f.lines().collect::<Vec<_>>();
        Some(lines.windows(2).map(|x| {
            Completion {
                completion: x[0].as_ref().unwrap().clone(),
                display: Some(x[1].as_ref().unwrap().clone()),
                suffix: None
            }
        }).collect())
    }
}

fn main() {
    let mut reader = Reader::new("test").unwrap();

    reader.set_prompt("> ");
    reader.set_completer(Rc::new(FooCompleter));

    while let Some(input) = reader.read_line().unwrap() {
        println!("foo: {}", input);
    }
}
```
## Data file:

[**out.txt**](https://github.com/murarth/linefeed/files/445331/out.txt)

Format is just pairs of lines for `completion` and `display` fields of Completion.
## Steps to reproduce:
- Run the test code, with the out.txt in the current directory
- Type k
- Press tab twice
- Observe panic

**Comment by tiffany352** [comment]
I've found a significantly more minimal testcase. No data file required. While writing this, I also discovered another panic on candidates which are zero in length.

``` rust
extern crate linefeed;

use linefeed::*;
use std::rc::Rc;

pub struct FooCompleter;

impl Completer<terminal::DefaultTerminal> for FooCompleter {
    fn complete(&self, _word: &str, _reader: &Reader<terminal::DefaultTerminal>,
                _start: usize, _end: usize) -> Option<Vec<Completion>> {
        use std::iter::repeat;
        let mut out = vec![];
        for i in 1..500 {
            let x = repeat('k').take(i).collect::<String>();
            out.push(Completion {
                completion: x.clone(),
                display: Some(x),
                suffix: None
            });
        }
        Some(out)
    }
}

fn main() {
    let mut reader = Reader::new("test").unwrap();

    reader.set_prompt("> ");
    reader.set_completer(Rc::new(FooCompleter));

    while let Some(input) = reader.read_line().unwrap() {
        println!("foo: {}", input);
    }
}
```

**Comment by murarth** [comment]
I've fixed both panicking cases and added tests. Thanks for the issue.
